### ISSUE TITLE
Overwrote my master branch

### ISSUE THREAD

**Issue by flcdrg** [meitar/jekyll-builder-for-github-pages-action#3]
Hi there,

i'm trying out your action for my blog.

I set up the secret_gh_pages_api_token and then discovered that the action had replaced my master branch.

https://github.com/flcdrg/flcdrg.github.io

I've turned off the secret_gh_pages_api_token for now, but that causes the action to fail.

The README seems to imply that for regular user accounts, it shouldn't be committing back to master?

**Comment by fabacab** [comment]
> The README seems to imply that for regular user accounts, it shouldn't be committing back to master?

Which part gives you that impression?

To be clear, the way this action works is by pushing the result of `jekyll build` to a GitHub branch so that it can be published by GitHub Pages. This necessarily means that you cannot have your raw source files (the *input to* `jekyll build`) be the same branch to which you push your finalized HTML code (the *output of* `jekyll build`).

If you are using this action to publish a GitHub Pages site for an Organization or User account, then you *MUST NOT* keep your source code in the `master` branch, since GitHub Pages reserves that branch for its GitHub Pages environment, i.e., the *output* of this action.

The above is a long-winded way of saying, "Yes, it probably did overwrite your `master` branch. That's what it's supposed to do."

**Comment by flcdrg** [comment]
Thanks for the quick response. I'd obviously misinterpreted "For User or Organization repositories, this option is completely ignored because those types of GitHub Pages sites can only ever use their master branch as a publishing source."

I was looking for a solution to getting GitHub pages to publish future-dated posts, but maybe this action isn't suited to my repository's structure.

**Comment by fabacab** [comment]
> I was looking for a solution to getting GitHub pages to publish future-dated posts, but maybe this action isn't suited to my repository's structure.

Jekyll can publish future-dated posts by suppying the `--future` flag. You want to [use the `jekyll_build_opts` option in this Action](https://github.com/meitar/jekyll-builder-for-github-pages-action#jekyll_build_opts).

> I'd obviously misinterpreted…

Yeah, that sounds like the root of the confusion. If you have suggestions for better phrasing in the README I'd happily accept a pull request.

**Comment by ovflowd** [comment]
That also happened with me, even reading the sentence I didn't get what the sentence was actually "implying".

I guess a rephrasing would work 😄 although I'm out of ideas right now.

**Comment by fabacab** [comment]
I gave it a shot but honestly I'm not sure how else to be clearer about this than I already am. I think you just have to be familiar with GitHub Pages, and the README as written does its best to encourage readers to read the GitHub Pages Help articles by deep-linking where appropriate. Hopefully the latest rephrasing helps but, again, I think this is just going to be something people have to experience to internalize.

**Comment by ovflowd** [comment]
Agreed 😄
